// Generated by gencpp from file motctrl_can/ack_fault.msg
// DO NOT EDIT!


#ifndef MOTCTRL_CAN_MESSAGE_ACK_FAULT_H
#define MOTCTRL_CAN_MESSAGE_ACK_FAULT_H

#include <ros/service_traits.h>


#include <motctrl_can/ack_faultRequest.h>
#include <motctrl_can/ack_faultResponse.h>


namespace motctrl_can
{

struct ack_fault
{

typedef ack_faultRequest Request;
typedef ack_faultResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ack_fault
} // namespace motctrl_can


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::motctrl_can::ack_fault > {
  static const char* value()
  {
    return "f4cf94077d46a7ac28e1686e63bb1b07";
  }

  static const char* value(const ::motctrl_can::ack_fault&) { return value(); }
};

template<>
struct DataType< ::motctrl_can::ack_fault > {
  static const char* value()
  {
    return "motctrl_can/ack_fault";
  }

  static const char* value(const ::motctrl_can::ack_fault&) { return value(); }
};


// service_traits::MD5Sum< ::motctrl_can::ack_faultRequest> should match
// service_traits::MD5Sum< ::motctrl_can::ack_fault >
template<>
struct MD5Sum< ::motctrl_can::ack_faultRequest>
{
  static const char* value()
  {
    return MD5Sum< ::motctrl_can::ack_fault >::value();
  }
  static const char* value(const ::motctrl_can::ack_faultRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::motctrl_can::ack_faultRequest> should match
// service_traits::DataType< ::motctrl_can::ack_fault >
template<>
struct DataType< ::motctrl_can::ack_faultRequest>
{
  static const char* value()
  {
    return DataType< ::motctrl_can::ack_fault >::value();
  }
  static const char* value(const ::motctrl_can::ack_faultRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::motctrl_can::ack_faultResponse> should match
// service_traits::MD5Sum< ::motctrl_can::ack_fault >
template<>
struct MD5Sum< ::motctrl_can::ack_faultResponse>
{
  static const char* value()
  {
    return MD5Sum< ::motctrl_can::ack_fault >::value();
  }
  static const char* value(const ::motctrl_can::ack_faultResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::motctrl_can::ack_faultResponse> should match
// service_traits::DataType< ::motctrl_can::ack_fault >
template<>
struct DataType< ::motctrl_can::ack_faultResponse>
{
  static const char* value()
  {
    return DataType< ::motctrl_can::ack_fault >::value();
  }
  static const char* value(const ::motctrl_can::ack_faultResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MOTCTRL_CAN_MESSAGE_ACK_FAULT_H
