// Generated by gencpp from file motctrl_can/get_fault.msg
// DO NOT EDIT!


#ifndef MOTCTRL_CAN_MESSAGE_GET_FAULT_H
#define MOTCTRL_CAN_MESSAGE_GET_FAULT_H

#include <ros/service_traits.h>


#include <motctrl_can/get_faultRequest.h>
#include <motctrl_can/get_faultResponse.h>


namespace motctrl_can
{

struct get_fault
{

typedef get_faultRequest Request;
typedef get_faultResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct get_fault
} // namespace motctrl_can


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::motctrl_can::get_fault > {
  static const char* value()
  {
    return "c1788c58a36cb063b2c61986779b5b3b";
  }

  static const char* value(const ::motctrl_can::get_fault&) { return value(); }
};

template<>
struct DataType< ::motctrl_can::get_fault > {
  static const char* value()
  {
    return "motctrl_can/get_fault";
  }

  static const char* value(const ::motctrl_can::get_fault&) { return value(); }
};


// service_traits::MD5Sum< ::motctrl_can::get_faultRequest> should match
// service_traits::MD5Sum< ::motctrl_can::get_fault >
template<>
struct MD5Sum< ::motctrl_can::get_faultRequest>
{
  static const char* value()
  {
    return MD5Sum< ::motctrl_can::get_fault >::value();
  }
  static const char* value(const ::motctrl_can::get_faultRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::motctrl_can::get_faultRequest> should match
// service_traits::DataType< ::motctrl_can::get_fault >
template<>
struct DataType< ::motctrl_can::get_faultRequest>
{
  static const char* value()
  {
    return DataType< ::motctrl_can::get_fault >::value();
  }
  static const char* value(const ::motctrl_can::get_faultRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::motctrl_can::get_faultResponse> should match
// service_traits::MD5Sum< ::motctrl_can::get_fault >
template<>
struct MD5Sum< ::motctrl_can::get_faultResponse>
{
  static const char* value()
  {
    return MD5Sum< ::motctrl_can::get_fault >::value();
  }
  static const char* value(const ::motctrl_can::get_faultResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::motctrl_can::get_faultResponse> should match
// service_traits::DataType< ::motctrl_can::get_fault >
template<>
struct DataType< ::motctrl_can::get_faultResponse>
{
  static const char* value()
  {
    return DataType< ::motctrl_can::get_fault >::value();
  }
  static const char* value(const ::motctrl_can::get_faultResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MOTCTRL_CAN_MESSAGE_GET_FAULT_H
