// Generated by gencpp from file motctrl_can/get_faultRequest.msg
// DO NOT EDIT!


#ifndef MOTCTRL_CAN_MESSAGE_GET_FAULTREQUEST_H
#define MOTCTRL_CAN_MESSAGE_GET_FAULTREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace motctrl_can
{
template <class ContainerAllocator>
struct get_faultRequest_
{
  typedef get_faultRequest_<ContainerAllocator> Type;

  get_faultRequest_()
    {
    }
  get_faultRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::motctrl_can::get_faultRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::motctrl_can::get_faultRequest_<ContainerAllocator> const> ConstPtr;

}; // struct get_faultRequest_

typedef ::motctrl_can::get_faultRequest_<std::allocator<void> > get_faultRequest;

typedef boost::shared_ptr< ::motctrl_can::get_faultRequest > get_faultRequestPtr;
typedef boost::shared_ptr< ::motctrl_can::get_faultRequest const> get_faultRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::motctrl_can::get_faultRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::motctrl_can::get_faultRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace motctrl_can

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::motctrl_can::get_faultRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::motctrl_can::get_faultRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::motctrl_can::get_faultRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::motctrl_can::get_faultRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::motctrl_can::get_faultRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::motctrl_can::get_faultRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::motctrl_can::get_faultRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::motctrl_can::get_faultRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::motctrl_can::get_faultRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "motctrl_can/get_faultRequest";
  }

  static const char* value(const ::motctrl_can::get_faultRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::motctrl_can::get_faultRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::motctrl_can::get_faultRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::motctrl_can::get_faultRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct get_faultRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::motctrl_can::get_faultRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::motctrl_can::get_faultRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // MOTCTRL_CAN_MESSAGE_GET_FAULTREQUEST_H
