// Generated by gencpp from file motctrl_can/get_version.msg
// DO NOT EDIT!


#ifndef MOTCTRL_CAN_MESSAGE_GET_VERSION_H
#define MOTCTRL_CAN_MESSAGE_GET_VERSION_H

#include <ros/service_traits.h>


#include <motctrl_can/get_versionRequest.h>
#include <motctrl_can/get_versionResponse.h>


namespace motctrl_can
{

struct get_version
{

typedef get_versionRequest Request;
typedef get_versionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct get_version
} // namespace motctrl_can


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::motctrl_can::get_version > {
  static const char* value()
  {
    return "df387e88f4e0b3094421061b0dcdbc29";
  }

  static const char* value(const ::motctrl_can::get_version&) { return value(); }
};

template<>
struct DataType< ::motctrl_can::get_version > {
  static const char* value()
  {
    return "motctrl_can/get_version";
  }

  static const char* value(const ::motctrl_can::get_version&) { return value(); }
};


// service_traits::MD5Sum< ::motctrl_can::get_versionRequest> should match
// service_traits::MD5Sum< ::motctrl_can::get_version >
template<>
struct MD5Sum< ::motctrl_can::get_versionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::motctrl_can::get_version >::value();
  }
  static const char* value(const ::motctrl_can::get_versionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::motctrl_can::get_versionRequest> should match
// service_traits::DataType< ::motctrl_can::get_version >
template<>
struct DataType< ::motctrl_can::get_versionRequest>
{
  static const char* value()
  {
    return DataType< ::motctrl_can::get_version >::value();
  }
  static const char* value(const ::motctrl_can::get_versionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::motctrl_can::get_versionResponse> should match
// service_traits::MD5Sum< ::motctrl_can::get_version >
template<>
struct MD5Sum< ::motctrl_can::get_versionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::motctrl_can::get_version >::value();
  }
  static const char* value(const ::motctrl_can::get_versionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::motctrl_can::get_versionResponse> should match
// service_traits::DataType< ::motctrl_can::get_version >
template<>
struct DataType< ::motctrl_can::get_versionResponse>
{
  static const char* value()
  {
    return DataType< ::motctrl_can::get_version >::value();
  }
  static const char* value(const ::motctrl_can::get_versionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MOTCTRL_CAN_MESSAGE_GET_VERSION_H
