// Generated by gencpp from file motctrl_can/modify_configuration.msg
// DO NOT EDIT!


#ifndef MOTCTRL_CAN_MESSAGE_MODIFY_CONFIGURATION_H
#define MOTCTRL_CAN_MESSAGE_MODIFY_CONFIGURATION_H

#include <ros/service_traits.h>


#include <motctrl_can/modify_configurationRequest.h>
#include <motctrl_can/modify_configurationResponse.h>


namespace motctrl_can
{

struct modify_configuration
{

typedef modify_configurationRequest Request;
typedef modify_configurationResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct modify_configuration
} // namespace motctrl_can


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::motctrl_can::modify_configuration > {
  static const char* value()
  {
    return "af0af68a5646388ca8f54851ea959ec8";
  }

  static const char* value(const ::motctrl_can::modify_configuration&) { return value(); }
};

template<>
struct DataType< ::motctrl_can::modify_configuration > {
  static const char* value()
  {
    return "motctrl_can/modify_configuration";
  }

  static const char* value(const ::motctrl_can::modify_configuration&) { return value(); }
};


// service_traits::MD5Sum< ::motctrl_can::modify_configurationRequest> should match
// service_traits::MD5Sum< ::motctrl_can::modify_configuration >
template<>
struct MD5Sum< ::motctrl_can::modify_configurationRequest>
{
  static const char* value()
  {
    return MD5Sum< ::motctrl_can::modify_configuration >::value();
  }
  static const char* value(const ::motctrl_can::modify_configurationRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::motctrl_can::modify_configurationRequest> should match
// service_traits::DataType< ::motctrl_can::modify_configuration >
template<>
struct DataType< ::motctrl_can::modify_configurationRequest>
{
  static const char* value()
  {
    return DataType< ::motctrl_can::modify_configuration >::value();
  }
  static const char* value(const ::motctrl_can::modify_configurationRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::motctrl_can::modify_configurationResponse> should match
// service_traits::MD5Sum< ::motctrl_can::modify_configuration >
template<>
struct MD5Sum< ::motctrl_can::modify_configurationResponse>
{
  static const char* value()
  {
    return MD5Sum< ::motctrl_can::modify_configuration >::value();
  }
  static const char* value(const ::motctrl_can::modify_configurationResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::motctrl_can::modify_configurationResponse> should match
// service_traits::DataType< ::motctrl_can::modify_configuration >
template<>
struct DataType< ::motctrl_can::modify_configurationResponse>
{
  static const char* value()
  {
    return DataType< ::motctrl_can::modify_configuration >::value();
  }
  static const char* value(const ::motctrl_can::modify_configurationResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MOTCTRL_CAN_MESSAGE_MODIFY_CONFIGURATION_H
