// Generated by gencpp from file motctrl_can/modify_parameterResponse.msg
// DO NOT EDIT!


#ifndef MOTCTRL_CAN_MESSAGE_MODIFY_PARAMETERRESPONSE_H
#define MOTCTRL_CAN_MESSAGE_MODIFY_PARAMETERRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace motctrl_can
{
template <class ContainerAllocator>
struct modify_parameterResponse_
{
  typedef modify_parameterResponse_<ContainerAllocator> Type;

  modify_parameterResponse_()
    : res(0)  {
    }
  modify_parameterResponse_(const ContainerAllocator& _alloc)
    : res(0)  {
  (void)_alloc;
    }



   typedef uint8_t _res_type;
  _res_type res;





  typedef boost::shared_ptr< ::motctrl_can::modify_parameterResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::motctrl_can::modify_parameterResponse_<ContainerAllocator> const> ConstPtr;

}; // struct modify_parameterResponse_

typedef ::motctrl_can::modify_parameterResponse_<std::allocator<void> > modify_parameterResponse;

typedef boost::shared_ptr< ::motctrl_can::modify_parameterResponse > modify_parameterResponsePtr;
typedef boost::shared_ptr< ::motctrl_can::modify_parameterResponse const> modify_parameterResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::motctrl_can::modify_parameterResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::motctrl_can::modify_parameterResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::motctrl_can::modify_parameterResponse_<ContainerAllocator1> & lhs, const ::motctrl_can::modify_parameterResponse_<ContainerAllocator2> & rhs)
{
  return lhs.res == rhs.res;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::motctrl_can::modify_parameterResponse_<ContainerAllocator1> & lhs, const ::motctrl_can::modify_parameterResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace motctrl_can

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::motctrl_can::modify_parameterResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::motctrl_can::modify_parameterResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::motctrl_can::modify_parameterResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::motctrl_can::modify_parameterResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::motctrl_can::modify_parameterResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::motctrl_can::modify_parameterResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::motctrl_can::modify_parameterResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f4cf94077d46a7ac28e1686e63bb1b07";
  }

  static const char* value(const ::motctrl_can::modify_parameterResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf4cf94077d46a7acULL;
  static const uint64_t static_value2 = 0x28e1686e63bb1b07ULL;
};

template<class ContainerAllocator>
struct DataType< ::motctrl_can::modify_parameterResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "motctrl_can/modify_parameterResponse";
  }

  static const char* value(const ::motctrl_can::modify_parameterResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::motctrl_can::modify_parameterResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 res\n"
;
  }

  static const char* value(const ::motctrl_can::modify_parameterResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::motctrl_can::modify_parameterResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.res);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct modify_parameterResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::motctrl_can::modify_parameterResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::motctrl_can::modify_parameterResponse_<ContainerAllocator>& v)
  {
    s << indent << "res: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.res);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MOTCTRL_CAN_MESSAGE_MODIFY_PARAMETERRESPONSE_H
