// Generated by gencpp from file motctrl_can/open_canRequest.msg
// DO NOT EDIT!


#ifndef MOTCTRL_CAN_MESSAGE_OPEN_CANREQUEST_H
#define MOTCTRL_CAN_MESSAGE_OPEN_CANREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace motctrl_can
{
template <class ContainerAllocator>
struct open_canRequest_
{
  typedef open_canRequest_<ContainerAllocator> Type;

  open_canRequest_()
    : canPort()
    , canID(0)  {
    }
  open_canRequest_(const ContainerAllocator& _alloc)
    : canPort(_alloc)
    , canID(0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _canPort_type;
  _canPort_type canPort;

   typedef uint32_t _canID_type;
  _canID_type canID;





  typedef boost::shared_ptr< ::motctrl_can::open_canRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::motctrl_can::open_canRequest_<ContainerAllocator> const> ConstPtr;

}; // struct open_canRequest_

typedef ::motctrl_can::open_canRequest_<std::allocator<void> > open_canRequest;

typedef boost::shared_ptr< ::motctrl_can::open_canRequest > open_canRequestPtr;
typedef boost::shared_ptr< ::motctrl_can::open_canRequest const> open_canRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::motctrl_can::open_canRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::motctrl_can::open_canRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::motctrl_can::open_canRequest_<ContainerAllocator1> & lhs, const ::motctrl_can::open_canRequest_<ContainerAllocator2> & rhs)
{
  return lhs.canPort == rhs.canPort &&
    lhs.canID == rhs.canID;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::motctrl_can::open_canRequest_<ContainerAllocator1> & lhs, const ::motctrl_can::open_canRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace motctrl_can

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::motctrl_can::open_canRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::motctrl_can::open_canRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::motctrl_can::open_canRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::motctrl_can::open_canRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::motctrl_can::open_canRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::motctrl_can::open_canRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::motctrl_can::open_canRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6f8785aaabb59bc5a8150a5766d93815";
  }

  static const char* value(const ::motctrl_can::open_canRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6f8785aaabb59bc5ULL;
  static const uint64_t static_value2 = 0xa8150a5766d93815ULL;
};

template<class ContainerAllocator>
struct DataType< ::motctrl_can::open_canRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "motctrl_can/open_canRequest";
  }

  static const char* value(const ::motctrl_can::open_canRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::motctrl_can::open_canRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string canPort\n"
"uint32 canID\n"
;
  }

  static const char* value(const ::motctrl_can::open_canRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::motctrl_can::open_canRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.canPort);
      stream.next(m.canID);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct open_canRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::motctrl_can::open_canRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::motctrl_can::open_canRequest_<ContainerAllocator>& v)
  {
    s << indent << "canPort: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.canPort);
    s << indent << "canID: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.canID);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MOTCTRL_CAN_MESSAGE_OPEN_CANREQUEST_H
