// Generated by gencpp from file motctrl_can/open_canResponse.msg
// DO NOT EDIT!


#ifndef MOTCTRL_CAN_MESSAGE_OPEN_CANRESPONSE_H
#define MOTCTRL_CAN_MESSAGE_OPEN_CANRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace motctrl_can
{
template <class ContainerAllocator>
struct open_canResponse_
{
  typedef open_canResponse_<ContainerAllocator> Type;

  open_canResponse_()
    : res(false)  {
    }
  open_canResponse_(const ContainerAllocator& _alloc)
    : res(false)  {
  (void)_alloc;
    }



   typedef uint8_t _res_type;
  _res_type res;





  typedef boost::shared_ptr< ::motctrl_can::open_canResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::motctrl_can::open_canResponse_<ContainerAllocator> const> ConstPtr;

}; // struct open_canResponse_

typedef ::motctrl_can::open_canResponse_<std::allocator<void> > open_canResponse;

typedef boost::shared_ptr< ::motctrl_can::open_canResponse > open_canResponsePtr;
typedef boost::shared_ptr< ::motctrl_can::open_canResponse const> open_canResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::motctrl_can::open_canResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::motctrl_can::open_canResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::motctrl_can::open_canResponse_<ContainerAllocator1> & lhs, const ::motctrl_can::open_canResponse_<ContainerAllocator2> & rhs)
{
  return lhs.res == rhs.res;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::motctrl_can::open_canResponse_<ContainerAllocator1> & lhs, const ::motctrl_can::open_canResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace motctrl_can

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::motctrl_can::open_canResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::motctrl_can::open_canResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::motctrl_can::open_canResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::motctrl_can::open_canResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::motctrl_can::open_canResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::motctrl_can::open_canResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::motctrl_can::open_canResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e27848a10f8e7e4030443887dfea101b";
  }

  static const char* value(const ::motctrl_can::open_canResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe27848a10f8e7e40ULL;
  static const uint64_t static_value2 = 0x30443887dfea101bULL;
};

template<class ContainerAllocator>
struct DataType< ::motctrl_can::open_canResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "motctrl_can/open_canResponse";
  }

  static const char* value(const ::motctrl_can::open_canResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::motctrl_can::open_canResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool res\n"
;
  }

  static const char* value(const ::motctrl_can::open_canResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::motctrl_can::open_canResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.res);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct open_canResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::motctrl_can::open_canResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::motctrl_can::open_canResponse_<ContainerAllocator>& v)
  {
    s << indent << "res: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.res);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MOTCTRL_CAN_MESSAGE_OPEN_CANRESPONSE_H
