// Generated by gencpp from file motctrl_can/open_can.msg
// DO NOT EDIT!


#ifndef MOTCTRL_CAN_MESSAGE_OPEN_CAN_H
#define MOTCTRL_CAN_MESSAGE_OPEN_CAN_H

#include <ros/service_traits.h>


#include <motctrl_can/open_canRequest.h>
#include <motctrl_can/open_canResponse.h>


namespace motctrl_can
{

struct open_can
{

typedef open_canRequest Request;
typedef open_canResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct open_can
} // namespace motctrl_can


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::motctrl_can::open_can > {
  static const char* value()
  {
    return "d49a54c9a4409020922fbcc3e9c6efc4";
  }

  static const char* value(const ::motctrl_can::open_can&) { return value(); }
};

template<>
struct DataType< ::motctrl_can::open_can > {
  static const char* value()
  {
    return "motctrl_can/open_can";
  }

  static const char* value(const ::motctrl_can::open_can&) { return value(); }
};


// service_traits::MD5Sum< ::motctrl_can::open_canRequest> should match
// service_traits::MD5Sum< ::motctrl_can::open_can >
template<>
struct MD5Sum< ::motctrl_can::open_canRequest>
{
  static const char* value()
  {
    return MD5Sum< ::motctrl_can::open_can >::value();
  }
  static const char* value(const ::motctrl_can::open_canRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::motctrl_can::open_canRequest> should match
// service_traits::DataType< ::motctrl_can::open_can >
template<>
struct DataType< ::motctrl_can::open_canRequest>
{
  static const char* value()
  {
    return DataType< ::motctrl_can::open_can >::value();
  }
  static const char* value(const ::motctrl_can::open_canRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::motctrl_can::open_canResponse> should match
// service_traits::MD5Sum< ::motctrl_can::open_can >
template<>
struct MD5Sum< ::motctrl_can::open_canResponse>
{
  static const char* value()
  {
    return MD5Sum< ::motctrl_can::open_can >::value();
  }
  static const char* value(const ::motctrl_can::open_canResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::motctrl_can::open_canResponse> should match
// service_traits::DataType< ::motctrl_can::open_can >
template<>
struct DataType< ::motctrl_can::open_canResponse>
{
  static const char* value()
  {
    return DataType< ::motctrl_can::open_can >::value();
  }
  static const char* value(const ::motctrl_can::open_canResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MOTCTRL_CAN_MESSAGE_OPEN_CAN_H
