// Generated by gencpp from file motctrl_can/position_controlRequest.msg
// DO NOT EDIT!


#ifndef MOTCTRL_CAN_MESSAGE_POSITION_CONTROLREQUEST_H
#define MOTCTRL_CAN_MESSAGE_POSITION_CONTROLREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace motctrl_can
{
template <class ContainerAllocator>
struct position_controlRequest_
{
  typedef position_controlRequest_<ContainerAllocator> Type;

  position_controlRequest_()
    : position(0.0)
    , duration(0)  {
    }
  position_controlRequest_(const ContainerAllocator& _alloc)
    : position(0.0)
    , duration(0)  {
  (void)_alloc;
    }



   typedef float _position_type;
  _position_type position;

   typedef uint32_t _duration_type;
  _duration_type duration;





  typedef boost::shared_ptr< ::motctrl_can::position_controlRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::motctrl_can::position_controlRequest_<ContainerAllocator> const> ConstPtr;

}; // struct position_controlRequest_

typedef ::motctrl_can::position_controlRequest_<std::allocator<void> > position_controlRequest;

typedef boost::shared_ptr< ::motctrl_can::position_controlRequest > position_controlRequestPtr;
typedef boost::shared_ptr< ::motctrl_can::position_controlRequest const> position_controlRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::motctrl_can::position_controlRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::motctrl_can::position_controlRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::motctrl_can::position_controlRequest_<ContainerAllocator1> & lhs, const ::motctrl_can::position_controlRequest_<ContainerAllocator2> & rhs)
{
  return lhs.position == rhs.position &&
    lhs.duration == rhs.duration;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::motctrl_can::position_controlRequest_<ContainerAllocator1> & lhs, const ::motctrl_can::position_controlRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace motctrl_can

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::motctrl_can::position_controlRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::motctrl_can::position_controlRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::motctrl_can::position_controlRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::motctrl_can::position_controlRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::motctrl_can::position_controlRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::motctrl_can::position_controlRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::motctrl_can::position_controlRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "41adcd0400e183bd56f3d0287c170111";
  }

  static const char* value(const ::motctrl_can::position_controlRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x41adcd0400e183bdULL;
  static const uint64_t static_value2 = 0x56f3d0287c170111ULL;
};

template<class ContainerAllocator>
struct DataType< ::motctrl_can::position_controlRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "motctrl_can/position_controlRequest";
  }

  static const char* value(const ::motctrl_can::position_controlRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::motctrl_can::position_controlRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 position\n"
"uint32 duration\n"
;
  }

  static const char* value(const ::motctrl_can::position_controlRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::motctrl_can::position_controlRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.position);
      stream.next(m.duration);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct position_controlRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::motctrl_can::position_controlRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::motctrl_can::position_controlRequest_<ContainerAllocator>& v)
  {
    s << indent << "position: ";
    Printer<float>::stream(s, indent + "  ", v.position);
    s << indent << "duration: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.duration);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MOTCTRL_CAN_MESSAGE_POSITION_CONTROLREQUEST_H
