// Generated by gencpp from file motctrl_can/retrieve_indicator.msg
// DO NOT EDIT!


#ifndef MOTCTRL_CAN_MESSAGE_RETRIEVE_INDICATOR_H
#define MOTCTRL_CAN_MESSAGE_RETRIEVE_INDICATOR_H

#include <ros/service_traits.h>


#include <motctrl_can/retrieve_indicatorRequest.h>
#include <motctrl_can/retrieve_indicatorResponse.h>


namespace motctrl_can
{

struct retrieve_indicator
{

typedef retrieve_indicatorRequest Request;
typedef retrieve_indicatorResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct retrieve_indicator
} // namespace motctrl_can


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::motctrl_can::retrieve_indicator > {
  static const char* value()
  {
    return "e3e36f0e5ef26f513e2b436e5ff969e7";
  }

  static const char* value(const ::motctrl_can::retrieve_indicator&) { return value(); }
};

template<>
struct DataType< ::motctrl_can::retrieve_indicator > {
  static const char* value()
  {
    return "motctrl_can/retrieve_indicator";
  }

  static const char* value(const ::motctrl_can::retrieve_indicator&) { return value(); }
};


// service_traits::MD5Sum< ::motctrl_can::retrieve_indicatorRequest> should match
// service_traits::MD5Sum< ::motctrl_can::retrieve_indicator >
template<>
struct MD5Sum< ::motctrl_can::retrieve_indicatorRequest>
{
  static const char* value()
  {
    return MD5Sum< ::motctrl_can::retrieve_indicator >::value();
  }
  static const char* value(const ::motctrl_can::retrieve_indicatorRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::motctrl_can::retrieve_indicatorRequest> should match
// service_traits::DataType< ::motctrl_can::retrieve_indicator >
template<>
struct DataType< ::motctrl_can::retrieve_indicatorRequest>
{
  static const char* value()
  {
    return DataType< ::motctrl_can::retrieve_indicator >::value();
  }
  static const char* value(const ::motctrl_can::retrieve_indicatorRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::motctrl_can::retrieve_indicatorResponse> should match
// service_traits::MD5Sum< ::motctrl_can::retrieve_indicator >
template<>
struct MD5Sum< ::motctrl_can::retrieve_indicatorResponse>
{
  static const char* value()
  {
    return MD5Sum< ::motctrl_can::retrieve_indicator >::value();
  }
  static const char* value(const ::motctrl_can::retrieve_indicatorResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::motctrl_can::retrieve_indicatorResponse> should match
// service_traits::DataType< ::motctrl_can::retrieve_indicator >
template<>
struct DataType< ::motctrl_can::retrieve_indicatorResponse>
{
  static const char* value()
  {
    return DataType< ::motctrl_can::retrieve_indicator >::value();
  }
  static const char* value(const ::motctrl_can::retrieve_indicatorResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MOTCTRL_CAN_MESSAGE_RETRIEVE_INDICATOR_H
