// Generated by gencpp from file motctrl_can/retrieve_configuration.msg
// DO NOT EDIT!


#ifndef MOTCTRL_CAN_MESSAGE_RETRIEVE_CONFIGURATION_H
#define MOTCTRL_CAN_MESSAGE_RETRIEVE_CONFIGURATION_H

#include <ros/service_traits.h>


#include <motctrl_can/retrieve_configurationRequest.h>
#include <motctrl_can/retrieve_configurationResponse.h>


namespace motctrl_can
{

struct retrieve_configuration
{

typedef retrieve_configurationRequest Request;
typedef retrieve_configurationResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct retrieve_configuration
} // namespace motctrl_can


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::motctrl_can::retrieve_configuration > {
  static const char* value()
  {
    return "4ecf154823b834945efbf15b2ed3cfb3";
  }

  static const char* value(const ::motctrl_can::retrieve_configuration&) { return value(); }
};

template<>
struct DataType< ::motctrl_can::retrieve_configuration > {
  static const char* value()
  {
    return "motctrl_can/retrieve_configuration";
  }

  static const char* value(const ::motctrl_can::retrieve_configuration&) { return value(); }
};


// service_traits::MD5Sum< ::motctrl_can::retrieve_configurationRequest> should match
// service_traits::MD5Sum< ::motctrl_can::retrieve_configuration >
template<>
struct MD5Sum< ::motctrl_can::retrieve_configurationRequest>
{
  static const char* value()
  {
    return MD5Sum< ::motctrl_can::retrieve_configuration >::value();
  }
  static const char* value(const ::motctrl_can::retrieve_configurationRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::motctrl_can::retrieve_configurationRequest> should match
// service_traits::DataType< ::motctrl_can::retrieve_configuration >
template<>
struct DataType< ::motctrl_can::retrieve_configurationRequest>
{
  static const char* value()
  {
    return DataType< ::motctrl_can::retrieve_configuration >::value();
  }
  static const char* value(const ::motctrl_can::retrieve_configurationRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::motctrl_can::retrieve_configurationResponse> should match
// service_traits::MD5Sum< ::motctrl_can::retrieve_configuration >
template<>
struct MD5Sum< ::motctrl_can::retrieve_configurationResponse>
{
  static const char* value()
  {
    return MD5Sum< ::motctrl_can::retrieve_configuration >::value();
  }
  static const char* value(const ::motctrl_can::retrieve_configurationResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::motctrl_can::retrieve_configurationResponse> should match
// service_traits::DataType< ::motctrl_can::retrieve_configuration >
template<>
struct DataType< ::motctrl_can::retrieve_configurationResponse>
{
  static const char* value()
  {
    return DataType< ::motctrl_can::retrieve_configuration >::value();
  }
  static const char* value(const ::motctrl_can::retrieve_configurationResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MOTCTRL_CAN_MESSAGE_RETRIEVE_CONFIGURATION_H
