// Generated by gencpp from file motctrl_can/retrieve_indicatorResponse.msg
// DO NOT EDIT!


#ifndef MOTCTRL_CAN_MESSAGE_RETRIEVE_INDICATORRESPONSE_H
#define MOTCTRL_CAN_MESSAGE_RETRIEVE_INDICATORRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace motctrl_can
{
template <class ContainerAllocator>
struct retrieve_indicatorResponse_
{
  typedef retrieve_indicatorResponse_<ContainerAllocator> Type;

  retrieve_indicatorResponse_()
    : res(0)
    , indiData(0.0)  {
    }
  retrieve_indicatorResponse_(const ContainerAllocator& _alloc)
    : res(0)
    , indiData(0.0)  {
  (void)_alloc;
    }



   typedef uint8_t _res_type;
  _res_type res;

   typedef float _indiData_type;
  _indiData_type indiData;





  typedef boost::shared_ptr< ::motctrl_can::retrieve_indicatorResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::motctrl_can::retrieve_indicatorResponse_<ContainerAllocator> const> ConstPtr;

}; // struct retrieve_indicatorResponse_

typedef ::motctrl_can::retrieve_indicatorResponse_<std::allocator<void> > retrieve_indicatorResponse;

typedef boost::shared_ptr< ::motctrl_can::retrieve_indicatorResponse > retrieve_indicatorResponsePtr;
typedef boost::shared_ptr< ::motctrl_can::retrieve_indicatorResponse const> retrieve_indicatorResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::motctrl_can::retrieve_indicatorResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::motctrl_can::retrieve_indicatorResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::motctrl_can::retrieve_indicatorResponse_<ContainerAllocator1> & lhs, const ::motctrl_can::retrieve_indicatorResponse_<ContainerAllocator2> & rhs)
{
  return lhs.res == rhs.res &&
    lhs.indiData == rhs.indiData;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::motctrl_can::retrieve_indicatorResponse_<ContainerAllocator1> & lhs, const ::motctrl_can::retrieve_indicatorResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace motctrl_can

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::motctrl_can::retrieve_indicatorResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::motctrl_can::retrieve_indicatorResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::motctrl_can::retrieve_indicatorResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::motctrl_can::retrieve_indicatorResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::motctrl_can::retrieve_indicatorResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::motctrl_can::retrieve_indicatorResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::motctrl_can::retrieve_indicatorResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "54dccc09add3d9c12a60ea78477d83ae";
  }

  static const char* value(const ::motctrl_can::retrieve_indicatorResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x54dccc09add3d9c1ULL;
  static const uint64_t static_value2 = 0x2a60ea78477d83aeULL;
};

template<class ContainerAllocator>
struct DataType< ::motctrl_can::retrieve_indicatorResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "motctrl_can/retrieve_indicatorResponse";
  }

  static const char* value(const ::motctrl_can::retrieve_indicatorResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::motctrl_can::retrieve_indicatorResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 res\n"
"float32 indiData\n"
;
  }

  static const char* value(const ::motctrl_can::retrieve_indicatorResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::motctrl_can::retrieve_indicatorResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.res);
      stream.next(m.indiData);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct retrieve_indicatorResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::motctrl_can::retrieve_indicatorResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::motctrl_can::retrieve_indicatorResponse_<ContainerAllocator>& v)
  {
    s << indent << "res: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.res);
    s << indent << "indiData: ";
    Printer<float>::stream(s, indent + "  ", v.indiData);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MOTCTRL_CAN_MESSAGE_RETRIEVE_INDICATORRESPONSE_H
