// Generated by gencpp from file motctrl_can/retrieve_parameterResponse.msg
// DO NOT EDIT!


#ifndef MOTCTRL_CAN_MESSAGE_RETRIEVE_PARAMETERRESPONSE_H
#define MOTCTRL_CAN_MESSAGE_RETRIEVE_PARAMETERRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace motctrl_can
{
template <class ContainerAllocator>
struct retrieve_parameterResponse_
{
  typedef retrieve_parameterResponse_<ContainerAllocator> Type;

  retrieve_parameterResponse_()
    : res(0)
    , paraData(0.0)  {
    }
  retrieve_parameterResponse_(const ContainerAllocator& _alloc)
    : res(0)
    , paraData(0.0)  {
  (void)_alloc;
    }



   typedef uint8_t _res_type;
  _res_type res;

   typedef float _paraData_type;
  _paraData_type paraData;





  typedef boost::shared_ptr< ::motctrl_can::retrieve_parameterResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::motctrl_can::retrieve_parameterResponse_<ContainerAllocator> const> ConstPtr;

}; // struct retrieve_parameterResponse_

typedef ::motctrl_can::retrieve_parameterResponse_<std::allocator<void> > retrieve_parameterResponse;

typedef boost::shared_ptr< ::motctrl_can::retrieve_parameterResponse > retrieve_parameterResponsePtr;
typedef boost::shared_ptr< ::motctrl_can::retrieve_parameterResponse const> retrieve_parameterResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::motctrl_can::retrieve_parameterResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::motctrl_can::retrieve_parameterResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::motctrl_can::retrieve_parameterResponse_<ContainerAllocator1> & lhs, const ::motctrl_can::retrieve_parameterResponse_<ContainerAllocator2> & rhs)
{
  return lhs.res == rhs.res &&
    lhs.paraData == rhs.paraData;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::motctrl_can::retrieve_parameterResponse_<ContainerAllocator1> & lhs, const ::motctrl_can::retrieve_parameterResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace motctrl_can

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::motctrl_can::retrieve_parameterResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::motctrl_can::retrieve_parameterResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::motctrl_can::retrieve_parameterResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::motctrl_can::retrieve_parameterResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::motctrl_can::retrieve_parameterResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::motctrl_can::retrieve_parameterResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::motctrl_can::retrieve_parameterResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fbb2309bdb65949cfcabb2111c1c4722";
  }

  static const char* value(const ::motctrl_can::retrieve_parameterResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xfbb2309bdb65949cULL;
  static const uint64_t static_value2 = 0xfcabb2111c1c4722ULL;
};

template<class ContainerAllocator>
struct DataType< ::motctrl_can::retrieve_parameterResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "motctrl_can/retrieve_parameterResponse";
  }

  static const char* value(const ::motctrl_can::retrieve_parameterResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::motctrl_can::retrieve_parameterResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 res\n"
"float32 paraData\n"
;
  }

  static const char* value(const ::motctrl_can::retrieve_parameterResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::motctrl_can::retrieve_parameterResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.res);
      stream.next(m.paraData);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct retrieve_parameterResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::motctrl_can::retrieve_parameterResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::motctrl_can::retrieve_parameterResponse_<ContainerAllocator>& v)
  {
    s << indent << "res: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.res);
    s << indent << "paraData: ";
    Printer<float>::stream(s, indent + "  ", v.paraData);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MOTCTRL_CAN_MESSAGE_RETRIEVE_PARAMETERRESPONSE_H
