// Generated by gencpp from file motctrl_can/retrieve_parameter.msg
// DO NOT EDIT!


#ifndef MOTCTRL_CAN_MESSAGE_RETRIEVE_PARAMETER_H
#define MOTCTRL_CAN_MESSAGE_RETRIEVE_PARAMETER_H

#include <ros/service_traits.h>


#include <motctrl_can/retrieve_parameterRequest.h>
#include <motctrl_can/retrieve_parameterResponse.h>


namespace motctrl_can
{

struct retrieve_parameter
{

typedef retrieve_parameterRequest Request;
typedef retrieve_parameterResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct retrieve_parameter
} // namespace motctrl_can


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::motctrl_can::retrieve_parameter > {
  static const char* value()
  {
    return "71f39d3d1e0d4e1df010337cf8fd203f";
  }

  static const char* value(const ::motctrl_can::retrieve_parameter&) { return value(); }
};

template<>
struct DataType< ::motctrl_can::retrieve_parameter > {
  static const char* value()
  {
    return "motctrl_can/retrieve_parameter";
  }

  static const char* value(const ::motctrl_can::retrieve_parameter&) { return value(); }
};


// service_traits::MD5Sum< ::motctrl_can::retrieve_parameterRequest> should match
// service_traits::MD5Sum< ::motctrl_can::retrieve_parameter >
template<>
struct MD5Sum< ::motctrl_can::retrieve_parameterRequest>
{
  static const char* value()
  {
    return MD5Sum< ::motctrl_can::retrieve_parameter >::value();
  }
  static const char* value(const ::motctrl_can::retrieve_parameterRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::motctrl_can::retrieve_parameterRequest> should match
// service_traits::DataType< ::motctrl_can::retrieve_parameter >
template<>
struct DataType< ::motctrl_can::retrieve_parameterRequest>
{
  static const char* value()
  {
    return DataType< ::motctrl_can::retrieve_parameter >::value();
  }
  static const char* value(const ::motctrl_can::retrieve_parameterRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::motctrl_can::retrieve_parameterResponse> should match
// service_traits::MD5Sum< ::motctrl_can::retrieve_parameter >
template<>
struct MD5Sum< ::motctrl_can::retrieve_parameterResponse>
{
  static const char* value()
  {
    return MD5Sum< ::motctrl_can::retrieve_parameter >::value();
  }
  static const char* value(const ::motctrl_can::retrieve_parameterResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::motctrl_can::retrieve_parameterResponse> should match
// service_traits::DataType< ::motctrl_can::retrieve_parameter >
template<>
struct DataType< ::motctrl_can::retrieve_parameterResponse>
{
  static const char* value()
  {
    return DataType< ::motctrl_can::retrieve_parameter >::value();
  }
  static const char* value(const ::motctrl_can::retrieve_parameterResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MOTCTRL_CAN_MESSAGE_RETRIEVE_PARAMETER_H
