// Generated by gencpp from file motctrl_can/retrieve_configurationResponse.msg
// DO NOT EDIT!


#ifndef MOTCTRL_CAN_MESSAGE_RETRIEVE_CONFIGURATIONRESPONSE_H
#define MOTCTRL_CAN_MESSAGE_RETRIEVE_CONFIGURATIONRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace motctrl_can
{
template <class ContainerAllocator>
struct retrieve_configurationResponse_
{
  typedef retrieve_configurationResponse_<ContainerAllocator> Type;

  retrieve_configurationResponse_()
    : res(0)
    , confData(0.0)  {
    }
  retrieve_configurationResponse_(const ContainerAllocator& _alloc)
    : res(0)
    , confData(0.0)  {
  (void)_alloc;
    }



   typedef uint8_t _res_type;
  _res_type res;

   typedef float _confData_type;
  _confData_type confData;





  typedef boost::shared_ptr< ::motctrl_can::retrieve_configurationResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::motctrl_can::retrieve_configurationResponse_<ContainerAllocator> const> ConstPtr;

}; // struct retrieve_configurationResponse_

typedef ::motctrl_can::retrieve_configurationResponse_<std::allocator<void> > retrieve_configurationResponse;

typedef boost::shared_ptr< ::motctrl_can::retrieve_configurationResponse > retrieve_configurationResponsePtr;
typedef boost::shared_ptr< ::motctrl_can::retrieve_configurationResponse const> retrieve_configurationResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::motctrl_can::retrieve_configurationResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::motctrl_can::retrieve_configurationResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::motctrl_can::retrieve_configurationResponse_<ContainerAllocator1> & lhs, const ::motctrl_can::retrieve_configurationResponse_<ContainerAllocator2> & rhs)
{
  return lhs.res == rhs.res &&
    lhs.confData == rhs.confData;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::motctrl_can::retrieve_configurationResponse_<ContainerAllocator1> & lhs, const ::motctrl_can::retrieve_configurationResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace motctrl_can

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::motctrl_can::retrieve_configurationResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::motctrl_can::retrieve_configurationResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::motctrl_can::retrieve_configurationResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::motctrl_can::retrieve_configurationResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::motctrl_can::retrieve_configurationResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::motctrl_can::retrieve_configurationResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::motctrl_can::retrieve_configurationResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "35c1e814444f32a3056e37f3ed33a437";
  }

  static const char* value(const ::motctrl_can::retrieve_configurationResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x35c1e814444f32a3ULL;
  static const uint64_t static_value2 = 0x056e37f3ed33a437ULL;
};

template<class ContainerAllocator>
struct DataType< ::motctrl_can::retrieve_configurationResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "motctrl_can/retrieve_configurationResponse";
  }

  static const char* value(const ::motctrl_can::retrieve_configurationResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::motctrl_can::retrieve_configurationResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 res\n"
"float32 confData\n"
;
  }

  static const char* value(const ::motctrl_can::retrieve_configurationResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::motctrl_can::retrieve_configurationResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.res);
      stream.next(m.confData);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct retrieve_configurationResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::motctrl_can::retrieve_configurationResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::motctrl_can::retrieve_configurationResponse_<ContainerAllocator>& v)
  {
    s << indent << "res: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.res);
    s << indent << "confData: ";
    Printer<float>::stream(s, indent + "  ", v.confData);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MOTCTRL_CAN_MESSAGE_RETRIEVE_CONFIGURATIONRESPONSE_H
