// Generated by gencpp from file motctrl_can/speed_control.msg
// DO NOT EDIT!


#ifndef MOTCTRL_CAN_MESSAGE_SPEED_CONTROL_H
#define MOTCTRL_CAN_MESSAGE_SPEED_CONTROL_H

#include <ros/service_traits.h>


#include <motctrl_can/speed_controlRequest.h>
#include <motctrl_can/speed_controlResponse.h>


namespace motctrl_can
{

struct speed_control
{

typedef speed_controlRequest Request;
typedef speed_controlResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct speed_control
} // namespace motctrl_can


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::motctrl_can::speed_control > {
  static const char* value()
  {
    return "8a067e4fd1b358d71a10a2e48cbbfc7e";
  }

  static const char* value(const ::motctrl_can::speed_control&) { return value(); }
};

template<>
struct DataType< ::motctrl_can::speed_control > {
  static const char* value()
  {
    return "motctrl_can/speed_control";
  }

  static const char* value(const ::motctrl_can::speed_control&) { return value(); }
};


// service_traits::MD5Sum< ::motctrl_can::speed_controlRequest> should match
// service_traits::MD5Sum< ::motctrl_can::speed_control >
template<>
struct MD5Sum< ::motctrl_can::speed_controlRequest>
{
  static const char* value()
  {
    return MD5Sum< ::motctrl_can::speed_control >::value();
  }
  static const char* value(const ::motctrl_can::speed_controlRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::motctrl_can::speed_controlRequest> should match
// service_traits::DataType< ::motctrl_can::speed_control >
template<>
struct DataType< ::motctrl_can::speed_controlRequest>
{
  static const char* value()
  {
    return DataType< ::motctrl_can::speed_control >::value();
  }
  static const char* value(const ::motctrl_can::speed_controlRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::motctrl_can::speed_controlResponse> should match
// service_traits::MD5Sum< ::motctrl_can::speed_control >
template<>
struct MD5Sum< ::motctrl_can::speed_controlResponse>
{
  static const char* value()
  {
    return MD5Sum< ::motctrl_can::speed_control >::value();
  }
  static const char* value(const ::motctrl_can::speed_controlResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::motctrl_can::speed_controlResponse> should match
// service_traits::DataType< ::motctrl_can::speed_control >
template<>
struct DataType< ::motctrl_can::speed_controlResponse>
{
  static const char* value()
  {
    return DataType< ::motctrl_can::speed_control >::value();
  }
  static const char* value(const ::motctrl_can::speed_controlResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MOTCTRL_CAN_MESSAGE_SPEED_CONTROL_H
