// Generated by gencpp from file motctrl_can/start_motor.msg
// DO NOT EDIT!


#ifndef MOTCTRL_CAN_MESSAGE_START_MOTOR_H
#define MOTCTRL_CAN_MESSAGE_START_MOTOR_H

#include <ros/service_traits.h>


#include <motctrl_can/start_motorRequest.h>
#include <motctrl_can/start_motorResponse.h>


namespace motctrl_can
{

struct start_motor
{

typedef start_motorRequest Request;
typedef start_motorResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct start_motor
} // namespace motctrl_can


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::motctrl_can::start_motor > {
  static const char* value()
  {
    return "f4cf94077d46a7ac28e1686e63bb1b07";
  }

  static const char* value(const ::motctrl_can::start_motor&) { return value(); }
};

template<>
struct DataType< ::motctrl_can::start_motor > {
  static const char* value()
  {
    return "motctrl_can/start_motor";
  }

  static const char* value(const ::motctrl_can::start_motor&) { return value(); }
};


// service_traits::MD5Sum< ::motctrl_can::start_motorRequest> should match
// service_traits::MD5Sum< ::motctrl_can::start_motor >
template<>
struct MD5Sum< ::motctrl_can::start_motorRequest>
{
  static const char* value()
  {
    return MD5Sum< ::motctrl_can::start_motor >::value();
  }
  static const char* value(const ::motctrl_can::start_motorRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::motctrl_can::start_motorRequest> should match
// service_traits::DataType< ::motctrl_can::start_motor >
template<>
struct DataType< ::motctrl_can::start_motorRequest>
{
  static const char* value()
  {
    return DataType< ::motctrl_can::start_motor >::value();
  }
  static const char* value(const ::motctrl_can::start_motorRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::motctrl_can::start_motorResponse> should match
// service_traits::MD5Sum< ::motctrl_can::start_motor >
template<>
struct MD5Sum< ::motctrl_can::start_motorResponse>
{
  static const char* value()
  {
    return MD5Sum< ::motctrl_can::start_motor >::value();
  }
  static const char* value(const ::motctrl_can::start_motorResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::motctrl_can::start_motorResponse> should match
// service_traits::DataType< ::motctrl_can::start_motor >
template<>
struct DataType< ::motctrl_can::start_motorResponse>
{
  static const char* value()
  {
    return DataType< ::motctrl_can::start_motor >::value();
  }
  static const char* value(const ::motctrl_can::start_motorResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MOTCTRL_CAN_MESSAGE_START_MOTOR_H
