// Generated by gencpp from file motctrl_can/stop_control.msg
// DO NOT EDIT!


#ifndef MOTCTRL_CAN_MESSAGE_STOP_CONTROL_H
#define MOTCTRL_CAN_MESSAGE_STOP_CONTROL_H

#include <ros/service_traits.h>


#include <motctrl_can/stop_controlRequest.h>
#include <motctrl_can/stop_controlResponse.h>


namespace motctrl_can
{

struct stop_control
{

typedef stop_controlRequest Request;
typedef stop_controlResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct stop_control
} // namespace motctrl_can


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::motctrl_can::stop_control > {
  static const char* value()
  {
    return "f4cf94077d46a7ac28e1686e63bb1b07";
  }

  static const char* value(const ::motctrl_can::stop_control&) { return value(); }
};

template<>
struct DataType< ::motctrl_can::stop_control > {
  static const char* value()
  {
    return "motctrl_can/stop_control";
  }

  static const char* value(const ::motctrl_can::stop_control&) { return value(); }
};


// service_traits::MD5Sum< ::motctrl_can::stop_controlRequest> should match
// service_traits::MD5Sum< ::motctrl_can::stop_control >
template<>
struct MD5Sum< ::motctrl_can::stop_controlRequest>
{
  static const char* value()
  {
    return MD5Sum< ::motctrl_can::stop_control >::value();
  }
  static const char* value(const ::motctrl_can::stop_controlRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::motctrl_can::stop_controlRequest> should match
// service_traits::DataType< ::motctrl_can::stop_control >
template<>
struct DataType< ::motctrl_can::stop_controlRequest>
{
  static const char* value()
  {
    return DataType< ::motctrl_can::stop_control >::value();
  }
  static const char* value(const ::motctrl_can::stop_controlRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::motctrl_can::stop_controlResponse> should match
// service_traits::MD5Sum< ::motctrl_can::stop_control >
template<>
struct MD5Sum< ::motctrl_can::stop_controlResponse>
{
  static const char* value()
  {
    return MD5Sum< ::motctrl_can::stop_control >::value();
  }
  static const char* value(const ::motctrl_can::stop_controlResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::motctrl_can::stop_controlResponse> should match
// service_traits::DataType< ::motctrl_can::stop_control >
template<>
struct DataType< ::motctrl_can::stop_controlResponse>
{
  static const char* value()
  {
    return DataType< ::motctrl_can::stop_control >::value();
  }
  static const char* value(const ::motctrl_can::stop_controlResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MOTCTRL_CAN_MESSAGE_STOP_CONTROL_H
